# Generated by Django 5.1.15 on 2026-08-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('doctor_name', models.CharField(max_length=255)),
                ('clinic_name', models.CharField(blank=True, default='', max_length=255)),
                ('prescription_date', models.DateField(db_index=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_dispensed', 'Partially Dispensed'), ('fully_dispensed', 'Fully Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='customers.customer')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-prescription_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
                'ordering': ['id'],
            },
        ),
    ]
