# Generated by Django 5.1.15 on 2026-08-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='customers.customer')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'db_table': 'returns',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restock', models.BooleanField(default=True, help_text='Should this item be added back to inventory?')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.batch')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
            ],
            options={
                'db_table': 'return_items',
                'ordering': ['id'],
            },
        ),
    ]
