# Generated by Django 5.1.15 on 2026-08-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(db_index=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_received', models.PositiveIntegerField(default=0)),
                ('current_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('empty', 'Empty'), ('quarantine', 'Quarantine')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='medicines.medicine')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
                'ordering': ['expiry_date', 'created_at'],
                'unique_together': {('batch_number', 'medicine')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase (In)'), ('sale', 'Sale (Out)'), ('return_in', 'Customer Return (In)'), ('return_out', 'Supplier Return (Out)'), ('adjustment_up', 'Manual Adjustment (Up)'), ('adjustment_down', 'Manual Adjustment (Down)'), ('damage', 'Damage/Spoilage (Out)'), ('expiry', 'Expiry (Out)'), ('transfer_in', 'Transfer (In)'), ('transfer_out', 'Transfer (Out)')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for inward, negative for outward')),
                ('reference_type', models.CharField(blank=True, default='', help_text="e.g., 'sale', 'purchase', 'adjustment'", max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
