# Generated by Django 5.1.15 on 2026-08-08 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('salary', 'Salary'), ('transportation', 'Transportation'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
