# Generated by Django 5.1.15 on 2026-08-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('generic_name', models.CharField(blank=True, default='', max_length=300)),
                ('brand_name', models.CharField(blank=True, default='', max_length=300)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('powder', 'Powder'), ('gel', 'Gel'), ('solution', 'Solution'), ('suspension', 'Suspension'), ('spray', 'Spray'), ('patch', 'Patch'), ('other', 'Other')], default='tablet', max_length=20)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g., 500mg, 10ml', max_length=100)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('box', 'Box'), ('strip', 'Strip'), ('bottle', 'Bottle'), ('tube', 'Tube'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('sachet', 'Sachet'), ('pack', 'Pack'), ('other', 'Other')], default='pcs', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_prescription', models.BooleanField(default=False)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('reorder_level', models.PositiveIntegerField(default=20)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='medicines.category')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.manufacturer')),
            ],
            options={
                'db_table': 'medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_name_017048_idx'), models.Index(fields=['generic_name'], name='medicines_generic_850df6_idx'), models.Index(fields=['barcode'], name='medicines_barcode_95be03_idx'), models.Index(fields=['status'], name='medicines_status_d9ff9b_idx')],
            },
        ),
    ]
